// Pure patch carrier: everything this package does lives in cordis.patch.yml
// (generated by scripts/gen_applist.py from applist.yaml, committed to the repo).
// No runtime code, same approach as @deepseek-ai/dsh-base.
export {};

